### PR TITLE
Add ability to build against gtk2 and gtk3

### PR DESCRIPTION
**Pull request by TingPing**
./configure now accepts both --with-gtk2 and --with-gtk3 defaulting to both.

### CODE REVIEW

**Comment by tschoonj** [comment]
@jralls would it be possible to merge this PR in? I think this is the best possible solution for having simultaneous support for both gtk2 and gtk3. I don't think a single library will every be possible since it would have to be linked against both gtk2 and gtk3 libraries which looks like a recipe for disaster...

**Comment by jralls** [comment]
OK, done. I thought that @TingPing was going to change it to have a gtk-mac-integration.pc for gtk2 and was waiting, then forgot.

**Comment by TingPing** [comment]
Yea sorry about that. A symlink is still a great idea but that issue existed before this PR.

**Comment by tschoonj** [comment]
Thanks a lot to the both of you!

Any chance you'll make a new release soon?

**Comment by TingPing** [comment]
> Any chance you'll make a new release soon?

As is a new release would break every user so I think adding that symlink before release is a wise idea. (Though gtk3 users are broken eitherway)

**Comment by jralls** [comment]
I started on a release yesterday but ran out of time, and I'm traveling for the rest of the week, so next week. 2.0.7 broke everything already w.r.t. gtk-mac-integration.pc, so it's not that important to add the symlink, but I agree it would be a nice touch. It can also be made for gtk3 when building only a gtk3 lib.

**Pull request merged**
